config/routes.rb
# Rails.application.routes.draw do
#   devise_for :users
#   root to: "pages#home"
#   # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Defines the root path route ("/")
#   # root "articles#index"
# end

Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :vacancies, only: %i[new update show]

  resources :users, only: :show do
    resources :applications, only: :index
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :vacancies, only: %i[new create show index edit update destroy] do
    resources :applications, only: %i[new create]
  end
  get '/applications/:id', to: 'application#destroy', as: :delete_application
  get '/users/:user_id/vacancies', to: 'vacancies#myvacancies', as: :my_vacancies
  # get '/islands/:id', to: 'islands#destroy', as: :delete_island
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :user
  belongs_to :vacancies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_many :vacancies
  has_many :applications
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  belongs_to :user

  has_many :applications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/applications_controller.rb
# class ApplicationsController < ApplicationController
#   before_action :set_island, only: %i[new create]
#   before_action :set_user, only: %i[new create]

#   def index
#     @bookings_i_made = Booking.where(user_id: current_user)
#     @bookings_requested_to_me = Booking.all.select do |booking|
#       current_user.islands.include?(booking.island)
#     end
#     # @bookings_requested_to_me.select do |booking|
#     #   current_user.islands.include?(booking.island)
#     # end
#   end

#   def update
#     @booking = Booking.find(params[:id])
#     @booking.accepted = true
#     if @booking.save
#       redirect_to user_bookings_path(current_user)
#     end
#   end

#   def destroy
#     @booking = Booking.find(params[:id])
#     @booking.destroy
#     redirect_to user_bookings_path(current_user), status: :see_other
#   end

#   def new
#     @booking = Booking.new
#   end

#   def show
#     @booking = Booking.find(params[:id])
#   end

#   def create
#     @booking = Booking.new(booking_params)
#     @booking.user = current_user
#     @booking.island = @island
#     @booking.price_per_night = @island.price
#     @booking.total_price = @booking.price_per_night * (@booking.end_date - @booking.start_date)
#     if @booking.save
#       redirect_to booking_path(@booking)
#     else
#       render :new, status: :unprocessable_entity, notice: 'The booking was not created.'
#     end
#   end

#   private

#   def set_island
#     @island = Island.find(params[:island_id])
#   end

#   def set_user
#     @island.user = current_user
#   end

#   def booking_params
#     params.require(:booking).permit(:island_id, :start_date, :end_date)
#   end
# end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController

  def index
    @vacancies = Vacancy.all
  end

  def show
    @vacancy = Vacancy.find(params[:id])
    # @booking = Booking.new
  end

  def new
    @vacancy = Vacancy.new
  end


  def create
    @vacancy = Vacancy.new(vacancy_params)
    @vacancy.user = current_user
    if @vacancy.save
      redirect_to vacancy_path(@vacancy), notice: 'Your vacancy was successfully created.'
    else
      render :new, status: :unprocessable_entity, notice: 'The vacancy was not created.'
    end
  end

  def edit
    @vacancy = Vacancy.find(params[:id])
  end

  def update
    @vacancy = Vacancy.find(params[:id])
    @vacancy.update(vacancy_params)
    redirect_to vacancy_path(@vacancy)
  end

  def destroy
    @vacancy = Vacancy.find(params[:id])
    @vacancy.destroy
    redirect_to my_vacancies_path(current_user), status: :see_other
  end

  private

  def vacancy_params
      params.require(:vacancy).permit(:job_title, :job_description, :job_location, :job_salary)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ablaze Jobs</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>JobFinder</h1>


<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>JobFinder brings <strong>employers</strong> to <strong>talented people</strong>!</h1>
    <p>Find the right role for you and change your life today</p>
    <div class="search-bar">
      <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get">
        <div class="search-form-control form-group">
          <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Enter Keyword ..." />
        </div>
        <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get">
        <div class="search-form-control form-group">
          <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder="Enter Location ..." />
        </div>
        <button name="button" type="submit" class="btn btn-gradient" >
          <i class="fas fa-search"></i> <a href="/vacancies">Find</a>
        </button>
      </form>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Ablaze Jobs
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <ul class="list-inline tabs-underlined">
      <li>
        <a href="#" class="tab-underlined active">Find Jobs</a>
      </li>
      <li>
        <a href="#" class="tab-underlined">CV Builder</a>
      </li>
      <li>
        <a href="#" class="tab-underlined">Company Reviews</a>
      </li>
    </ul>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%= link_to "Add Vacancy", new_vacancy_path, class: "nav-link" if user_signed_in?%>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/vacancies/index.html.erb
<div class="main-container d-flex justify-content-between">
  <div class="container bg-white" style="height: 835px;" id="card-containers">
    <div class="row">
      <% @vacancies.each do |vacancy| %>
        <div class="col-lg-3">
          <%= link_to vacancy_path(vacancy), class:"text-decoration-none picture" do %>
            <div class="card-trip">
              <div class="card-trip-infos">
                <div>
                  <h1><%= vacancy.job_title %></h1>
                  <h2><%= vacancy.job_location %></h2>
                  <p><%= vacancy.job_description %></p>
                </div>
                <h2 class="card-trip-pricing">£<%= vacancy.job_salary %></h2>
                <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> %>
              </div>
            </div>
          <% end %>
         </div>
      <% end %>
    </div>
  </div>
</div>

app/views/vacancies/new.html.erb
<div class="container" style="width: 50%">
  <%= simple_form_for @vacancy do |f| %>
    <%= f.input :job_title %>
    <%= f.input :job_description %>
    <%= f.input :job_location %>
    <%= f.input :job_salary%>
    <%= f.button :submit, class: "btn-search" %>
  <% end %>
</div>

app/views/vacancies/show.html.erb
<div class="box">
  <div class="card">
    <div>
      <h5>Location:</h5>
      <h3><%= @vacancy.job_location %></h3>
      <h5>---------------------------<h5>
      <h5>Description:</h5>
      <h3><%= @vacancy.job_description %></h3>
      <h5>---------------------------<h5>
      <h5>Salary:</h5>
      <h3>£ <%= @vacancy.job_salary %> per shift</h3>
      <h5>---------------------------<h5>
    </div>